services:
  postgres:
    image: postgres:16
    container_name: gymclub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gymclub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - gymclub-postgres-data:/var/lib/postgresql/data

volumes:
  gymclub-postgres-data:
